name = "esp32s3"


[rust]
detect = [{ file = "Cargo.toml", key = "edition" }]
layer = [{ cmd = "FROM rust:${var}", var = { file = "rust-toolchain.toml", key = "channel" } }]

[rust.cargo.rustc.xtensaesp32s3noneelf.esphal]
detect = [{ file = "Cargo.toml", key = "esp-hal" }]
layer = ["RUN rustup target add xtensa-esp32s3-none-elf"]
cmd = "cargo build"

[rust.cargo.rustc.xtensaesp32s3noneelf.espidf]
detect = [{ file = "Cargo.toml", key = "esp-idf-svc" }]
layer = ["RUN rustup target add xtensa-esp32s3-none-elf"]
cmd = "cargo build"

