name = "rp2350"

[rust]
detect = [{ file = "Cargo.toml", key = "edition" }]
layer = [{ cmd = "FROM rust:${var}", var = { file = "rust-toolchain.toml", key = "channel" } }]

[rust.cargo.rustc.thumbv8mmainnoneeabihf]
detect = [{ file = ".cargo/config.toml", key = "thumbv8m.main-none-eabihf" }]
layer = [
    "RUN rustup target add thumbv8m.main-none-eabihf",
    "RUN cargo install flip-link",
]
cmd = "cargo build"

# [c]
# detect = [{ file = "CMakeLists.txt", key = "cmake_minimum_required" }]
#
# [c.cmake.gcc.armnoneabi.picosdk]
# detect = [{ file = "CMakeLists.txt", key = "pico_sdk" }]
# layer = ["FROM ghcr.io/getfork/rp2350/c-cmake-gcc-armnoneabi-picosdk:latest"]
# cmd = "cmake -B build . && make -C build"
#
# [arduino]
# detect = [{ file = "*.ino" }]
# layer = ["FROM ghcr.io/getfork/rp2350/arduinocli:latest"]
# cmd = "arduino-cli core install rp2040:rp2040 --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json && arduino-cli compile --fqbn rp2040:rp2040:rpipico2 --output-dir build ."
#
# [micropython]
# detect = [{ file = "main.py", key = "import machine" }]
# layer = ["FROM ghcr.io/getfork/micropython:latest"]
# cmd = "mpy-cross main.py"
