name = "stm32f405"

[rust]
detect = [{ file = "Cargo.toml", key = "edition" }]
layer = [{ cmd = "FROM rust:${var}", var = { file = "rust-toolchain.toml", key = "channel" } }]

[rust.cargo.rustc.thumbv7emnoneeabihf]
detect = [{ file = ".cargo/config.toml", key = "thumbv7em-none-eabihf" }]
layer = ["RUN rustup target add thumbv7em-none-eabihf"]
cmd = "cargo build"

[c]
detect = [{ file = "CMakeLists.txt", key = "cmake_minimum_required" }]

[c.cmake.gcc.armnoneabi.stm32cube]
detect = [{ file = "CMakeLists.txt", key = "stm32" }]
layer = ["FROM ghcr.io/getfork/stm32f405/c-cmake-gcc-armnoneabi-stm32cube:latest"]
cmd = "cmake -B build . && make -C build"

[arduino]
detect = [{ file = "*.ino" }]
layer = ["FROM ghcr.io/getfork/stm32f405/arduinocli:latest"]
cmd = "arduino-cli core install STMicroelectronics:stm32 --additional-urls https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json && arduino-cli compile --fqbn STMicroelectronics:stm32:GenF4 --output-dir build ."
